# Generated by Django 6.0.3 on 2026-03-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Student_Register',
        ),
    ]
